<?php

return [
    'sign_in' => 'Login',
    'go_to_login' => 'Go to Login',
    'failed' => 'These credentials do not match our records.',

    'forgot_password' => [
        'label' => 'Forgot password?',
        'label_help' => 'Enter your account email address to receive instructions on resetting your password.',
        'button' => 'Recover Account',
    ],

    'reset_password' => [
        'button' => 'Reset and Login',
    ],

    'two_factor' => [
        'label' => 'Two-Factor Token',
        'label_help' => 'This account requires a second layer of authentication to continue. Please enter the code generated by your device to complete this login.',
        'checkpoint_failed' => 'The two-factor authentication token is invalid.',
    ],

    'throttle' => 'Too many login attempts. Please try again in :seconds seconds.',
    'password_requirements' => 'Passwords must be at least 8 characters in length and should be unique to this site.',
    '2fa_must_be_enabled' => 'The administrator has required that two-factor authentication be enabled for your account to use the panel.',
];
